name: storybook
type: drupal11
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: true

# Codespaces settings
host_webserver_port: "8080"
host_https_port: "8443"
host_db_port: "3306"
router_http_port: "8080"
router_https_port: "8443"
performance_mode: mutagen

hooks:
  post-start:
    - exec-host: "ddev import-db --file=db/site.sql.gz  && ddev drush cim -y && ddev drush cr"
    - exec: "echo ✅ DB import After Start......."

  pre-stop:
     - exec-host: "ddev drush cr && ddev drush cex -y && ddev drush sql-dump --gzip --result-file=../db/site.sql"
