name: storybook
type: drupal11
docroot: web
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: true

# Codespaces settings
router_http_port: "8080"
router_https_port: "8443"
performance_mode: mutagen

hooks:
  post-start:
    - exec: |
        echo "📦 Installing Composer dependencies..."
        composer install --no-interaction --prefer-dist --optimize-autoloader
        echo "✅ Composer install complete"
    - exec-host: |
        echo "🔄 Waiting for DDEV to be fully ready..."
        sleep 10
        echo "📥 Importing database..."
        if [ -f "db/site.sql.gz" ]; then
          ddev import-db --file=db/site.sql.gz
          echo "✅ Database imported successfully"
        else
          echo "❌ Database file not found at db/site.sql.gz"
        fi
        echo "⚙️ Importing configuration..."
        ddev drush cim -y
        echo "🧹 Clearing cache..."
        ddev drush cr
        echo "✅ Post-start setup complete!"
    - exec: "echo '✅ DDEV environment is ready for development'"

  pre-stop:
    - exec-host: |
        echo "🧹 Clearing cache before export..."
        ddev drush cr
        echo "⚙️ Exporting configuration..."
        ddev drush cex -y
        echo "💾 Exporting database..."
        mkdir -p db
        ddev drush sql-dump --gzip --result-file=../db/site.sql
        echo "✅ Pre-stop backup complete!"
